# Catppuccino theme scheme for Alacritty

[colors.primary]
background = '#1E1E2E'
foreground = '#d6d6d6'

[colors.cursor]
text = '#CDD6F4'
cursor = '#D9D9D9'

[colors.normal]
black = '#181A1F'
red = '#E86671'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#54AFBC'
white = '#ABB2BF'

[colors.bright]
black = "#585B70" 
red = "#F38BA8"
green = "#A6E3A1"
yellow = "#F9E2AF"
blue = "#89B4FA"
magenta = "#F5C2E7"
cyan = "#94E2D5"
white = "#A6ADC8"

[colors.dim]
black = '#5C6370'
red = '#74423f'
green = '#98C379'
yellow = '#E5C07B'
blue = '#61AFEF'
magenta = '#6e4962'
cyan = '#5c8482'
white = '#828282'
